Starting with Data exploration.

In [1]:
import pandas as pd

df = pd.read_csv('Housing_Habitability_Dataset.csv')
print("--- First 5 Rows ---")
display(df.head())
print("\n--- Dataframe Info ---")
df.info()

--- First 5 Rows ---

,Property_ID,Property_Type,Property_Area,Number_of_Windows,Number_of_Doors,Furnishing,Frequency_of_Powercuts,Power_Backup,Water_Supply,Traffic_Density_Score,Crime_Rate,Dust_and_Noise,Air_Quality_Index,Neighborhood_Review,Habitability_score
0,0x21e3,Apartment,106,NaN,1,Semi_Furnished,0.0,No,Once in a day - Morning,5.89,Slightly below average,Medium,90,3.86,71.98
1,0x68d4,Apartment,733,2.0,2,Unfurnished,1.0,No,Once in a day - Evening,4.37,Well below average,Medium,96,3.55,71.20
2,0x7d81,Apartment,737,4.0,2,Fully Furnished,0.0,No,Once in a day - Morning,7.45,Slightly below average,Medium,121,3.81,71.39
3,0x7a57,Apartment,900,3.0,2,Unfurnished,2.0,Yes,Once in a day - Morning,6.16,Well above average,Medium,100,1.34,31.46
4,0x9409,Bungalow,2238,14.0,6,Fully Furnished,0.0,No,All time,5.46,Well below average,Medium,116,4.77,93.70

--- Dataframe Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35549 entries, 0 to 35548
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Property_ID             35549 non-null  object
 1   Property_Type           35549 non-null  object
 2   Property_Area           35549 non-null  int64
 3   Number_of_Windows       34059 non-null  float64
 4   Number_of_Doors         35549 non-null  int64
 5   Furnishing              34620 non-null  object
 6   Frequency_of_Powercuts  34296 non-null  float64
 7   Power_Backup            35549 non-null  object
 8   Water_Supply            35549 non-null  object
 9   Traffic_Density_Score   35549 non-null  float64
 10  Crime_Rate              34828 non-null  object
 11  Dust_and_Noise          34441 non-null  object
 12  Air_Quality_Index       35549 non-null  int64
 13  Neighborhood_Review     35549 non-null  float64
 14  Habitability_score      35549 non-null  float64
dtypes: float64(5), int64(3), object(7)
memory usage: 4.1+ MB

The Dataset has many null values and contains strings.
Lets handle the missing values.

In [2]:
# Get the sum of missing values for each column
df.isnull().sum()

Property_ID                  0
Property_Type                0
Property_Area                0
Number_of_Windows         1490
Number_of_Doors              0
Furnishing                 929
Frequency_of_Powercuts    1253
Power_Backup                 0
Water_Supply                 0
Traffic_Density_Score        0
Crime_Rate                 721
Dust_and_Noise            1108
Air_Quality_Index            0
Neighborhood_Review          0
Habitability_score           0
dtype: int64

In [3]:
# Impute (fill) missing numerical values with the median
for col in ['Number_of_Windows', 'Frequency_of_Powercuts']:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)

# Impute (fill) missing categorical values with the mode
for col in ['Furnishing', 'Crime_Rate', 'Dust_and_Noise']:
    mode_val = df[col].mode()[0]
    df[col].fillna(mode_val, inplace=True)

# Let's verify that all missing values are handled
print("Missing values after filling:")
print(df.isnull().sum())

Missing values after filling:
Property_ID               0
Property_Type             0
Property_Area             0
Number_of_Windows         0
Number_of_Doors           0
Furnishing                0
Frequency_of_Powercuts    0
Power_Backup              0
Water_Supply              0
Traffic_Density_Score     0
Crime_Rate                0
Dust_and_Noise            0
Air_Quality_Index         0
Neighborhood_Review       0
Habitability_score        0
dtype: int64

C:\Users\Dinesh\AppData\Local\Temp\ipykernel_17840\378975669.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)
C:\Users\Dinesh\AppData\Local\Temp\ipykernel_17840\378975669.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)
C:\Users\Dinesh\AppData\Local\Temp\ipykernel_17840\378975669.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)

Now handling the objects in the dataset

In [4]:
# Drop the Property_ID as it's just an identifier and not a useful feature
df.drop('Property_ID', axis=1, inplace=True)

# Use get_dummies to one-hot encode all categorical columns
df_processed = pd.get_dummies(df, drop_first=True)

# Display the first few rows of the new processed dataframe
print("--- Processed Dataframe Head ---")
display(df_processed.head())

# Check the new dataframe's info to see the changes
print("\n--- Processed Dataframe Info ---")
df_processed.info()

--- Processed Dataframe Head ---

,Property_Area,Number_of_Windows,Number_of_Doors,Frequency_of_Powercuts,Traffic_Density_Score,Air_Quality_Index,Neighborhood_Review,Habitability_score,Property_Type_Apartment,Property_Type_Bungalow,...,Power_Backup_Yes,Water_Supply_NOT MENTIONED,Water_Supply_Once in a day - Evening,Water_Supply_Once in a day - Morning,Water_Supply_Once in two days,Crime_Rate_Slightly below average,Crime_Rate_Well above average,Crime_Rate_Well below average,Dust_and_Noise_Low,Dust_and_Noise_Medium
0,106,4.0,1,0.0,5.89,90,3.86,71.98,True,False,...,False,False,False,True,False,True,False,False,False,True
1,733,2.0,2,1.0,4.37,96,3.55,71.20,True,False,...,False,False,True,False,False,False,False,True,False,True
2,737,4.0,2,0.0,7.45,121,3.81,71.39,True,False,...,False,False,False,True,False,True,False,False,False,True
3,900,3.0,2,2.0,6.16,100,1.34,31.46,True,False,...,True,False,False,True,False,False,True,False,False,True
4,2238,14.0,6,0.0,5.46,116,4.77,93.70,False,True,...,False,False,False,False,False,False,False,True,False,True

--- Processed Dataframe Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35549 entries, 0 to 35548
Data columns (total 26 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Property_Area                         35549 non-null  int64
 1   Number_of_Windows                     35549 non-null  float64
 2   Number_of_Doors                       35549 non-null  int64
 3   Frequency_of_Powercuts                35549 non-null  float64
 4   Traffic_Density_Score                 35549 non-null  float64
 5   Air_Quality_Index                     35549 non-null  int64
 6   Neighborhood_Review                   35549 non-null  float64
 7   Habitability_score                    35549 non-null  float64
 8   Property_Type_Apartment               35549 non-null  bool
 9   Property_Type_Bungalow                35549 non-null  bool
 10  Property_Type_Container Home          35549 non-null  bool
 11  Property_Type_Duplex                  35549 non-null  bool
 12  Property_Type_Single-family home      35549 non-null  bool
 13  Furnishing_Semi_Furnished             35549 non-null  bool
 14  Furnishing_Unfurnished                35549 non-null  bool
 15  Power_Backup_No                       35549 non-null  bool
 16  Power_Backup_Yes                      35549 non-null  bool
 17  Water_Supply_NOT MENTIONED            35549 non-null  bool
 18  Water_Supply_Once in a day - Evening  35549 non-null  bool
 19  Water_Supply_Once in a day - Morning  35549 non-null  bool
 20  Water_Supply_Once in two days         35549 non-null  bool
 21  Crime_Rate_Slightly below average     35549 non-null  bool
 22  Crime_Rate_Well above average         35549 non-null  bool
 23  Crime_Rate_Well below average         35549 non-null  bool
 24  Dust_and_Noise_Low                    35549 non-null  bool
 25  Dust_and_Noise_Medium                 35549 non-null  bool
dtypes: bool(18), float64(5), int64(3)
memory usage: 2.8 MB

Problems with the dataset are handled as we can see there is Null values and Objects. 
Lets move on with separating the features and target

In [5]:
# X gets all the columns EXCEPT for 'Habitability_score'
X = df_processed.drop('Habitability_score', axis=1)

# y gets ONLY the 'Habitability_score' column
y = df_processed['Habitability_score']

# Let's check the shape of our new variables to confirm
print(f"Shape of our features (X): {X.shape}")
print(f"Shape of our target (y): {y.shape}")

Shape of our features (X): (35549, 25)
Shape of our target (y): (35549,)

Now the datum is ready-to-feed to the model.

Starting the Model training

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import joblib

In [7]:
# Split the data (80% for training, 20% for testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Training data shape: {X_train.shape}")
print(f"Testing data shape: {X_test.shape}")

Training data shape: (28439, 25)
Testing data shape: (7110, 25)

Saving the Columns of the Model

In [8]:
joblib.dump(X_train.columns, 'Dataset_ColumnsAlone.joblib')
print("Dataset columns saved successfully!")

Dataset columns saved successfully!

Implementing the Model - Random Forest.

In [9]:
# We set n_jobs=-1 to use all your computer's CPU cores to make it faster
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)

Training the model on the training data.

In [10]:
print("\nStarting model training...")
model.fit(X_train, y_train)
print("Model training complete!")

Starting model training...
Model training complete!

Saving the Model

In [11]:
joblib.dump((X_train, y_train), 'Trained_HH_Model.joblib')
print("Model saved successfully as 'Trained_HH_Model.joblib'")

# Saving the test data for evaluation later
joblib.dump((X_test, y_test), 'Test_Dataset.joblib')
print("Test data saved successfully.")

Model saved successfully as 'Trained_HH_Model.joblib'
Test data saved successfully.